workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never

stages:
  - deploy
  - ping

deploy-to-server:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh docker-cli
    - echo "$SSH_KEY" > id_ed25519
    - chmod 400 id_ed25519
  script:
    - |
      ssh -o StrictHostKeyChecking=no -i id_ed25519 $SSH_USER@$SSH_HOST "
        cd /opt/nocodi_backend && \
        docker compose -f compose.yaml up -d --build --no-deps migration backend && \
        echo '✅ Compose build and up complete. Showing backend logs...' && \
        docker compose logs -n 50 backend
      "
  after_script:
    - rm -f id_ed25519

# ping-google:
#   stage: ping
#   image: curlimages/curl:latest
#   script:
#     - echo "🌐 Pinging google..."
#     - curl -I https://www.google.com
