services:
  redis:
    image: redis:7
    command: ["redis-server"]
    ports:
      - "6380:6379"
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: nocodi
      POSTGRES_USER: nocodi
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
