# Generated by Django 5.1.7 on 2025-06-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="iamuser",
            name="last_login_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
