# Generated by Django 5.1.7 on 2025-03-08 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="iamuser",
            name="status",
        ),
    ]
