# Generated by Django 5.1.7 on 2025-05-09 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("component", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="previous_component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_component",
                to="component.component",
            ),
        ),
    ]
