# Generated by Django 5.1.7 on 2025-04-24 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("component", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendmessage",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    ("model", "inlinekeyboardmarkup"),
                    ("model", "replykeyboardmarkup"),
                    ("model", "replykeyboardremove"),
                    ("model", "forcereply"),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
