# Generated by Django 5.1.7 on 2025-06-19 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("component", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetData",
            fields=[
                (
                    "component_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="component.component",
                    ),
                ),
                ("data", models.JSONField(help_text="Data to set")),
                ("key", models.CharField(help_text="Key to set data", max_length=255)),
            ],
            bases=("component.component",),
        ),
        migrations.AlterField(
            model_name="component",
            name="component_type",
            field=models.CharField(
                choices=[
                    ("TELEGRAM", "Telegram API Component"),
                    ("TRIGGER", "Trigger Component"),
                    ("CONDITIONAL", "Conditional Component"),
                    ("CODE", "Code Component"),
                    ("STATE", "State Component"),
                    ("DATA", "Data Component"),
                ],
                default="TELEGRAM",
                help_text="Type of the component",
                max_length=20,
            ),
        ),
    ]
