# Generated by Django 5.1.7 on 2025-04-25 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("component", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copymessage",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("model", "inlinekeyboardmarkup"),
                    ("model", "replykeyboardmarkup"),
                    ("model", "replykeyboardremove"),
                    ("model", "forcereply"),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="editmessagecaption",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("model", "inlinekeyboardmarkup")),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="editmessagelivelocation",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("model", "inlinekeyboardmarkup")),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="editmessagemedia",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("model", "inlinekeyboardmarkup")),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="editmessagereplymarkup",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("model", "inlinekeyboardmarkup")),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="editmessagetext",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("model", "inlinekeyboardmarkup")),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="sendanimation",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("model", "inlinekeyboardmarkup"),
                    ("model", "replykeyboardmarkup"),
                    ("model", "replykeyboardremove"),
                    ("model", "forcereply"),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="sendcontact",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("model", "inlinekeyboardmarkup"),
                    ("model", "replykeyboardmarkup"),
                    ("model", "replykeyboardremove"),
                    ("model", "forcereply"),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="senddice",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("model", "inlinekeyboardmarkup"),
                    ("model", "replykeyboardmarkup"),
                    ("model", "replykeyboardremove"),
                    ("model", "forcereply"),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="senddocument",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("model", "inlinekeyboardmarkup"),
                    ("model", "replykeyboardmarkup"),
                    ("model", "replykeyboardremove"),
                    ("model", "forcereply"),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="sendgame",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("model", "inlinekeyboardmarkup")),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="sendinvoice",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("model", "inlinekeyboardmarkup")),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="sendlocation",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("model", "inlinekeyboardmarkup"),
                    ("model", "replykeyboardmarkup"),
                    ("model", "replykeyboardremove"),
                    ("model", "forcereply"),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="sendmessage",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("model", "inlinekeyboardmarkup"),
                    ("model", "replykeyboardmarkup"),
                    ("model", "replykeyboardremove"),
                    ("model", "forcereply"),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="sendpaidmedia",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("model", "inlinekeyboardmarkup"),
                    ("model", "replykeyboardmarkup"),
                    ("model", "replykeyboardremove"),
                    ("model", "forcereply"),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="sendphoto",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("model", "inlinekeyboardmarkup"),
                    ("model", "replykeyboardmarkup"),
                    ("model", "replykeyboardremove"),
                    ("model", "forcereply"),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="sendpoll",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("model", "inlinekeyboardmarkup"),
                    ("model", "replykeyboardmarkup"),
                    ("model", "replykeyboardremove"),
                    ("model", "forcereply"),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="sendsticker",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("model", "inlinekeyboardmarkup"),
                    ("model", "replykeyboardmarkup"),
                    ("model", "replykeyboardremove"),
                    ("model", "forcereply"),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="sendvenue",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("model", "inlinekeyboardmarkup"),
                    ("model", "replykeyboardmarkup"),
                    ("model", "replykeyboardremove"),
                    ("model", "forcereply"),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="sendvideo",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("model", "inlinekeyboardmarkup"),
                    ("model", "replykeyboardmarkup"),
                    ("model", "replykeyboardremove"),
                    ("model", "forcereply"),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="sendvideonote",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("model", "inlinekeyboardmarkup"),
                    ("model", "replykeyboardmarkup"),
                    ("model", "replykeyboardremove"),
                    ("model", "forcereply"),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="sendvoice",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("model", "inlinekeyboardmarkup"),
                    ("model", "replykeyboardmarkup"),
                    ("model", "replykeyboardremove"),
                    ("model", "forcereply"),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="stopmessagelivelocation",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("model", "inlinekeyboardmarkup")),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="stoppoll",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("model", "inlinekeyboardmarkup")),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
