# Generated by Django 5.1.7 on 2025-04-12 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("component", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IfComponent",
            fields=[
                (
                    "component_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="component.component",
                    ),
                ),
                ("expression", models.CharField(max_length=1024)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("Equal", "Equal"),
                            ("Contains", "Contains"),
                            ("Greater", "Greater"),
                            ("GreaterEqual", "Greaterequal"),
                        ],
                        max_length=40,
                    ),
                ),
                ("is_reverse", models.BooleanField(default=False)),
            ],
            bases=("component.component",),
        ),
    ]
