# Generated by Django 5.1.7 on 2025-04-12 12:02

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("component", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeComponent",
            fields=[
                (
                    "component_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="component.component",
                    ),
                ),
                ("code", models.TextField()),
            ],
            bases=("component.component",),
        ),
        migrations.CreateModel(
            name="SwithComponent",
            fields=[
                (
                    "component_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="component.component",
                    ),
                ),
                ("expression", models.CharField(max_length=1024)),
                (
                    "values",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1024),
                        size=None,
                    ),
                ),
            ],
            bases=("component.component",),
        ),
    ]
