# Generated by Django 5.1.7 on 2025-04-24 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
        ("component", "0002_alter_sendmessage_content_type"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="component",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="component",
            name="bot",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="bot.bot",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="component",
            name="component_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="component_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="component",
            name="position_x",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="component",
            name="position_y",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="component",
            name="previous_component",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="next_component",
                to="component.component",
            ),
        ),
    ]
