# Generated by Django 5.1.7 on 2025-06-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("component", "0002_setdata_alter_component_component_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setdata",
            name="data",
            field=models.CharField(blank=True, help_text="Data to set", null=True),
        ),
        migrations.AlterField(
            model_name="setdata",
            name="key",
            field=models.CharField(
                blank=True,
                help_text="Key to set data",
                max_length=255,
                null=True,
            ),
        ),
    ]
