# Generated by Django 5.1.7 on 2025-05-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("component", "0002_alter_component_previous_component"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codecomponent",
            name="code",
            field=models.TextField(blank=True, help_text="Code to execute", null=True),
        ),
    ]
