# Generated by Django 5.1.7 on 2025-08-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("component", "0003_alter_setdata_data_alter_setdata_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copymessage",
            name="caption",
            field=models.TextField(
                blank=True,
                help_text="New caption for media, 0-1024 characters after entities parsing. If not specified, the original caption is kept",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="editmessagecaption",
            name="caption",
            field=models.TextField(
                blank=True,
                help_text="New caption of the message, 0-1024 characters after entities parsing",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="editmessagetext",
            name="text",
            field=models.TextField(
                blank=True,
                help_text="New text of the message, 1-4096 characters after entities parsing",
                max_length=4096,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="editstory",
            name="caption",
            field=models.TextField(
                blank=True,
                help_text="Caption of the story, 0-2048 characters after entities parsing",
                max_length=2048,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="giftpremiumsubscription",
            name="text",
            field=models.TextField(
                blank=True,
                help_text="Text that will be shown along with the service message about the subscription; 0-128 characters",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="poststory",
            name="caption",
            field=models.TextField(
                blank=True,
                help_text="Caption of the story, 0-2048 characters after entities parsing",
                max_length=2048,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sendanimation",
            name="caption",
            field=models.TextField(
                blank=True,
                help_text="Animation caption (may also be used when resending animation by file_id), 0-1024 characters after entities parsing",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="senddocument",
            name="caption",
            field=models.TextField(
                blank=True,
                help_text="Document caption (may also be used when resending documents by file_id), 0-1024 characters after entities parsing",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sendgift",
            name="text",
            field=models.TextField(
                blank=True,
                help_text="Text that will be shown along with the gift; 0-128 characters",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sendmessage",
            name="text",
            field=models.TextField(
                blank=True,
                help_text="Text of the message to be sent, 1-4096 characters after entities parsing",
                max_length=4096,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sendpaidmedia",
            name="caption",
            field=models.TextField(
                blank=True,
                help_text="Media caption, 0-1024 characters after entities parsing",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sendphoto",
            name="caption",
            field=models.TextField(
                blank=True,
                help_text="Photo caption (may also be used when resending photos by file_id), 0-1024 characters after entities parsing",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sendvideo",
            name="caption",
            field=models.TextField(
                blank=True,
                help_text="Video caption (may also be used when resending videos by file_id), 0-1024 characters after entities parsing",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sendvoice",
            name="caption",
            field=models.TextField(
                blank=True,
                help_text="Voice message caption, 0-1024 characters after entities parsing",
                max_length=1024,
                null=True,
            ),
        ),
    ]
