# Generated by Django 5.1.7 on 2025-06-05 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("component", "0003_alter_codecomponent_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Markup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "markup_type",
                    models.CharField(
                        choices=[
                            ("InlineKeyboard", "Inlinekeyboard"),
                            ("ReplyKeyboard", "Replykeyboard"),
                        ],
                        help_text="Markup type",
                        max_length=20,
                    ),
                ),
                ("buttons", models.JSONField(help_text="Buttons to use")),
                (
                    "parent_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markup",
                        to="component.component",
                    ),
                ),
            ],
        ),
    ]
