# Generated by Django 5.1.7 on 2025-06-06 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("component", "0004_markup"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetState",
            fields=[
                (
                    "component_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="component.component",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="Name of state. Should not contain comma",
                        max_length=4096,
                        null=True,
                    ),
                ),
            ],
            bases=("component.component",),
        ),
        migrations.AddField(
            model_name="onmessage",
            name="state",
            field=models.CharField(
                blank=True,
                help_text="Optional comma separated list of states to match. If not specified, matches any state.",
                max_length=4096,
                null=True,
            ),
        ),
    ]
