# Generated by Django 5.1.7 on 2025-06-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("component", "0005_setstate_onmessage_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="component_type",
            field=models.CharField(
                choices=[
                    ("TELEGRAM", "Telegram API Component"),
                    ("TRIGGER", "Trigger Component"),
                    ("CONDITIONAL", "Conditional Component"),
                    ("CODE", "Code Component"),
                    ("STATE", "State Component"),
                ],
                default="TELEGRAM",
                help_text="Type of the component",
                max_length=20,
            ),
        ),
    ]
