# Generated by Django 5.1.7 on 2025-06-08 10:34

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("component", "0006_alter_component_component_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ifcomponent",
            name="component_ptr",
        ),
        migrations.AddField(
            model_name="switchcomponent",
            name="next_components",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="markup",
            name="parent_component",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="markup",
                to="component.component",
            ),
        ),
        migrations.AddConstraint(
            model_name="switchcomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(False),
                name="check_next_components_length",
            ),
        ),
        migrations.DeleteModel(
            name="IfComponent",
        ),
    ]
