# Generated by Django 5.1.7 on 2025-06-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("component", "0007_remove_ifcomponent_component_ptr_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OnCallbackQuery",
        ),
    ]
