# Generated by Django 5.1.7 on 2025-04-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
