# Generated by Django 5.1.7 on 2025-03-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="token",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
