# Generated by Django 5.1.7 on 2025-04-24 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("component", "0003_remove_component_timestamp_component_bot_and_more"),
        ("flow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="start_component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="component.component",
            ),
        ),
        migrations.RemoveField(
            model_name="terminal",
            name="flow",
        ),
        migrations.DeleteModel(
            name="Component",
        ),
        migrations.DeleteModel(
            name="Terminal",
        ),
    ]
